### ISSUE TITLE
Githubteacher-todo

### ISSUE THREAD

**Issue by githubteacher** [githubteacher/everyone-march-hcanna#1]
# GitHub for Everyone Todo List

### List

- Learn GitHub.com
- Learn how to work locally with GitHub Desktop
- Learn Project Management tools

**Comment by githubteacher** [comment]
@githubstudent and @hcanna will you please take a look at this for :eyes: and clarity?

**Comment by hcanna** [comment]
:ship: please @hcanna

**Comment by githubteacher** [comment]
@githubstudent ... I need your :+1: to :ship: as well?

**Comment by githubteacher** [comment]
### List for what we are doing in class today.

- [ ] Learn GitHub.com

- [ ] Learn to work Locally

- [ ] Learn Project Management Tools

**Comment by githubteacher** [comment]
@hcanna .... I just need a moment of your :clock1:

**Comment by githubteacher** [comment]
- [ ] Todo step 1
- [ ] Todo step 2
